name: Full CI/CD
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release (i.e.: 1.2.0)'
        required: true
      next_version:
        description: 'Next development cycle version (i.e.: 1.3.0-SNAPSHOT)'
        required: true

jobs:
  build:
    name: Build on Commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sonarqube: [ 9.9.0.65466 ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set Release Version ${{ github.event.inputs.release_version }}
        if: github.event_name == 'workflow_dispatch' && matrix.sonarqube == '9.9.0.65466'
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.release_version }} -DgenerateBackupPoms=false

      - name: Build and Test against SonarQube ${{ matrix.sonarqube }}
        run: mvn -B clean verify -Pits -"Dsonar.runtimeVersion=${{ matrix.sonarqube }}"

      - name: Run SonarQube Analysis
        if: contains(github.ref, 'main') && matrix.sonarqube == '9.9.0.65466'
        run: mvn -B sonar:sonar -Dsonar.login=${{ secrets.SONARQUBE_SCANNER_FOR_PRIVATE_REPOSITORIES_TOKEN }}

      - name: Upload Plugin JAR
        if: matrix.sonarqube == '9.9.0.65466'
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: |
            sonar-gcov-plugin/target/sonar-gcov-plugin-*.jar
            !sonar-gcov-plugin/target/sonar-gcov-plugin-*-sources.jar

      - name: Commit, Push and Tag Release Version ${{ github.event.inputs.release_version }}
        if: github.event_name == 'workflow_dispatch' && matrix.sonarqube == '9.9.0.65466'
        uses: EndBug/add-and-commit@v9
        with:
          add: '*'
          author_name: GitHub Actions
          author_email: github-actions@linty-services.com
          message: Release version ${{ github.event.inputs.release_version }}
          tag: ${{ github.event.inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Release Commit Hash
        if: matrix.sonarqube == '9.9.0.65466'
        run: echo $(git rev-parse HEAD) >> release_commit.txt

      - name: Set Next Development Cycle Version ${{ github.event.inputs.next_version }}
        if: github.event_name == 'workflow_dispatch' && matrix.sonarqube == '9.9.0.65466'
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.next_version }} -DgenerateBackupPoms=false

      - name: Commit and Push Next Development Cycle Version ${{ github.event.inputs.next_version }}
        if: github.event_name == 'workflow_dispatch' && matrix.sonarqube == '9.9.0.65466'
        uses: EndBug/add-and-commit@v9
        with:
          add: '*'
          author_name: GitHub Actions
          author_email: github-actions@linty-services.com
          message: Bump version to ${{ github.event.inputs.next_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Commit Hash
        if: matrix.sonarqube == '9.9.0.65466'
        run: echo $(git rev-parse HEAD) >> latest_commit.txt

      - name: Upload Commit Hashes
        if: matrix.sonarqube == '9.9.0.65466'
        uses: actions/upload-artifact@v3
        with:
          name: commits
          path: |
            release_commit.txt
            latest_commit.txt

  pre-release:
    name: GitHub Pre-release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'main')
    steps:
      - name: Download Plugin JAR
        uses: actions/download-artifact@v3
        with:
          name: plugin

      - name: Rename JAR into latest
        run: mv sonar-gcov-plugin-*.jar sonar-gcov-plugin-latest.jar

      - name: Download Commit Hashes
        uses: actions/download-artifact@v3
        with:
          name: commits

      - name: Read Latest Commit Hash
        run: echo "LATEST_COMMIT=$(cat latest_commit.txt)" >> $GITHUB_ENV

      - name: Delete latest Release
        run: gh release delete latest -R Linty-Services/sonar-gcov-plugin --cleanup-tag -y
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "GitHub Release: latest"
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          artifacts: sonar-gcov-plugin-latest.jar
          name: Latest build from main
          prerelease: true
          commit: ${{ env.LATEST_COMMIT }}

  release:
    name: GitHub Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Download Plugin JAR
        uses: actions/download-artifact@v3
        with:
          name: plugin

      - name: Download Commit Hashes
        uses: actions/download-artifact@v3
        with:
          name: commits

      - name: Read Release Commit Hash
        run: echo "RELEASE_COMMIT=$(cat release_commit.txt)" >> $GITHUB_ENV

      - name: "GitHub Release: ${{ github.event.inputs.release_version }}"
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_version }}
          artifacts: sonar-gcov-plugin-*.jar
          name: ${{ github.event.inputs.release_version }}
          commit: ${{ env.RELEASE_COMMIT }}

      - name: "Close Milestone ${{ github.event.inputs.release_version }}"
        uses: Akkjon/close-milestone@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          milestone_name: ${{ github.event.inputs.release_version }}
